### ISSUE TITLE
Clarify difference with Stata's HC2 and HC3 weighted estimator

### ISSUE THREAD

**Issue by lukesonnet** [DeclareDesign/estimatr#108]

**Comment by lukesonnet** [comment]
This is done, I shared it on Slack a while ago. I'm happy to add it to the "Technical Notes" dropdown on the website or just post it to my own website and link it on the website if it is clutter for the main page.

**Comment by graemeblair** [comment]
I think great to add this -- guarantee this question will come up if we don't clarify diff ("I'm getting something different, what's wrong with your code!")

**Comment by lukesonnet** [comment]
I think that's the right call
