### ISSUE TITLE
Better argument error handling

### ISSUE THREAD

**Issue by lukesonnet** [DeclareDesign/estimatr#11]
Check that arguments being passed to lm_robust are correct, and return informative errors if not:

- se_type that is not one of the allowed
- coefficient name that isn't in the model
- weights or cluster variable that aren't in the data frame
- weights that are non-numeric
- weights must be non-negative (?)

Mimic `check_randomizr_arguments`

**Comment by lukesonnet** [comment]
Actually, do you guys have a strong preference for a standalone argument checker? I think I'd rather handle checks as they come up and instead focus on speed.

**Comment by graemeblair** [comment]
That works for me. I think speed is most important here.

**Comment by lukesonnet** [comment]
Okay, this is wrapped up in getting code coverage up, and the issues listed above I've covered.
