### ISSUE TITLE
Ask for cplot.default method from margins

### ISSUE THREAD

**Issue by lukesonnet** [DeclareDesign/estimatr#111]
Once on CRAN, should we ask @leeper to change `cplot.lm` to `cplot.default` as `cplot.lm` works with `"lm_robust"` objects but users have to call it like so `margins:::cplot.lm()`?

Seems like most model objects have what `cplot.lm` wants. We could also consider writing our own wrapper.

**Comment by leeper** [comment]
I can probably do this. Can you open an issue about it?

**Comment by lukesonnet** [comment]
Sure, will do!

**Comment by leeper** [comment]
This is now implemented in margins.

**Comment by graemeblair** [comment]
Closing this. Thanks so much @leeper - really happy about this full integration!
