### ISSUE TITLE
Refactor clean_model_data NSE to use rlang

### ISSUE THREAD

**Issue by nfultz** [DeclareDesign/estimatr#114]
This is still a rough patch present in each estimator.

**Comment by lukesonnet** [comment]
In this process, we should also drop regressors that are from factors that have empty labels on the cleaned data (ie. remove from the model matrix columns from factors that are constant).

**Comment by lukesonnet** [comment]
This is done by #141, but I want to leave this open until I add some rlang compatibility tests.
