### ISSUE TITLE
moving commarobust() to estimatr

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/estimatr#116]
We're going to move the function commarobust() from the commarobust package. 

It should take an lm object and return tidy df with robust standard errors that looks exactly the same as lm_robust. 

We're going to deprecate the functionality of the commarobust package and push people to this.

**Comment by acoppock** [comment]
Awesome. the commarobust package also has this nifty hack for stargazer.  Someday I'd love it if we could get estimatr into stargazer...

**Comment by lukesonnet** [comment]
Bumping this to version 0.8.0
