### ISSUE TITLE
Post-launch publication of estimatr

### ISSUE THREAD

**Issue by lukesonnet** [DeclareDesign/estimatr#117]
Add as an answer to SO posts such as the following

- https://stats.stackexchange.com/questions/117052/replicating-statas-robust-option-in-r/117066
- https://stackoverflow.com/questions/4385436/regression-with-heteroskedasticity-corrected-standard-errors
- https://stackoverflow.com/questions/13789303/robust-se-vcovhc-to-be-shown-with-texreg-in-r?rq=1
- If IV is finished, also add as answer to IV robust SE questions

Give a talk at CCPR showing off the functionality?
Give a talk to Saad G's experiments class at Stanford.

**Comment by graemeblair** [comment]
Nice! After we publish the blog post!
