### ISSUE TITLE
add support for leeper/prediction

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/estimatr#122]
Flip side of the coin of margins. Presumably a similar API so shouldn't be too hard to add support on our side / maybe it already works.

https://cran.r-project.org/web/packages/prediction/index.html

**Comment by lukesonnet** [comment]
This works out of the box with OLS thanks to leeper's awesome "find_data()" function. In fact we should rec this instead of our own predict S3 method.

I'll add a nod to it in the getting started vignette.
