### ISSUE TITLE
texreg behavior

### ISSUE THREAD

**Issue by acoppock** [DeclareDesign/estimatr#136]
Any ideas why texreg wont display SEs?  It only shows CIs....

```
library(texreg)

dat <- fabricate(
  N = 40,
  y = rpois(N, lambda = 4),
  x = rnorm(N),
  z = rbinom(N, 1, prob = 0.4)
)

lmrout <- lm_robust(y ~ x + z, data = dat)
texregobj <- extract(lmrout)

# Doesn't report SEs?
texreg(texregobj)
texreg(texregobj, ci.force = FALSE)
```

**Comment by acoppock** [comment]
I know this is small potatoes, but it's INTERRUPTING MY WORKFLOW.

**Comment by graemeblair** [comment]
seems like PR is in order too, no?

**Comment by lukesonnet** [comment]
I wanted to just clear the other PR first, but rewriting the variance handling for multiple outcomes is taking some time, so I'll just PR the fix for this and the fix for intercept-only models (#144). The fix for #139 is bound up in PR #141. Will get to it in a minute.

**Comment by lukesonnet** [comment]
Oh I see what you mean. Yah I'll raise an issue or PR as well.

**Comment by lukesonnet** [comment]
Hmmm, none of this should really work. You should be doing:

```
texreg(lmrout)
```
anyways.

**Comment by lukesonnet** [comment]
In which case `texreg(lmrout, include.ci = FALSE)` works as intended, so I'm not going to issue. It's a choice they've made which in our case defaults to CIs and there's a reasonable solution.

**Comment by acoppock** [comment]
looks like this one's all set!
