### ISSUE TITLE
residual variance is always from classical estimator

### ISSUE THREAD

**Issue by lukesonnet** [DeclareDesign/estimatr#138]
Should be different for different variance estimators

**Comment by nfultz** [comment]
Is this related to your anova implementation, or somethign else?

**Comment by lukesonnet** [comment]
Yes.

**Comment by lukesonnet** [comment]
This is going to get bumped, mostly because I don't totally understand in why it would be different under heteroskedasticity since we still need a fixed value for the r.squared. Maybe renaming it would be more appropriate?

**Comment by lukesonnet** [comment]
This as stated was incorrect, the problem was that the fstat's were always relying on the residual variance which is only permissible with spherical errors. This issue has been resolved.
