### ISSUE TITLE
iv_robust

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/estimatr#14]
A new function that mimics the functionality of `lm_robust` i.e. using Rcpp but for IV regression. The idea is to have a faster, simpler version of the IV functions that are out there and to do the right things re: standard errors. Tricky bit will be the formula.

**Comment by lukesonnet** [comment]
This is implemented by #141! Doesn't have ancillary tests, but F-test, coefficients, R-squared all match stata and ivpack/ivreg given the right condiitons.
