### ISSUE TITLE
estimatr::tidy.lm_robust column headers

### ISSUE THREAD

**Issue by conjugateprior** [DeclareDesign/estimatr#146]
`broom:::tidy.lm` generates column headers: `term`, `estimate`, `std.error`, `statistic`, `p.value`, `conf.low`, `conf.high` and `outcome`, with `broom::glance` providing `df`.

`estimatr::tidy.lm_robust` names them `coefficient_name`, `coefficients`, `se`, `p`, `ci_lower`, `ci_upper`, `df`,  and `outcome`. 

Is there a reason for this? If not, would you accept a PR to bring these into line with `broom`? (Context: I'd like to be able to do similar things to all sorts of *tidy*-ed models).

**Comment by nfultz** [comment]
I think we would be generally open to this, but there needs to be a corresponding change in https://github.com/DeclareDesign/DeclareDesign where difference_in_mean et all are used -- I can coordinate that.

**Comment by lukesonnet** [comment]
Implemented by #173 

Changes in DD should follow!

**Comment by graemeblair** [comment]
Thanks for the suggestion Will @conjugateprior!
