### ISSUE TITLE
drop blocks 

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/estimatr#147]
+1 to Macartan's suggestion:

d-i- m can  produce this:
`## Error: Must have units with both treatment conditions within each block.`

woudn't it be better to be better to count the block as contributing nothing and give a warning -- as does OLS

**Comment by lukesonnet** [comment]
I think I have this working appropriately when there are blocks with no treatment variation (that is, save for the degrees of freedom, the estimate and se are the same as if you dropped the blocks with constant treatment before estimating).

```r
devtools::install_github("DeclareDesign/estimatr@ls/blocks_dim")
bldat <- data.frame(bl = rep(1:3, each = 4), 
                      z = c(0, 0, 0, 0, rep(0:1, times = 4)),
                      y = rnorm(12))
table(bldat$bl, bldat$z)
# Same save for the df
difference_in_means(y ~ z, blocks = bl, data = bldat)
```
```
Design:  Blocked 
   Estimate Std. Error  Pr(>|t|)  CI Lower CI Upper DF
z 0.8027258   1.084293 0.4802654 -1.697659 3.303111  8
Warning message:
In difference_in_means(y ~ z, blocks = bl, data = bldat) :
  1 blocks dropped for containing no variation in treatment
```
```r
difference_in_means(y ~ z, blocks = bl, data = bldat, subset = bl != 1)
```
```
Design:  Blocked 
   Estimate Std. Error  Pr(>|t|)  CI Lower CI Upper DF
z 0.8027258   1.084293 0.5002042 -2.207755 3.813207  4
```
```r
lm_lin(y ~ z, ~ factor(bl), data = bldat, subset = bl != 1)
```
```
                  Estimate Std. Error   Pr(>|t|)  CI Lower   CI Upper DF
(Intercept)     -0.9848382  0.2757746 0.02335127 -1.750511 -0.2191651  4
z                0.8027258  1.0842933 0.50020421 -2.207755  3.8132065  4
factor(bl)3_c   -0.6264591  0.5515492 0.31946991 -2.157805  0.9048870  4
z:factor(bl)3_c  1.0210992  2.1685865 0.66227091 -4.999862  7.0420606  4
```

However, the results are different if we estimate `lm_lin` with the full data. It strikes me that our d-i-m estimate is the correct one because `lm_lin` is demeaning the block dummies as if all the blocks are going to be used.

```r
lm_lin(y ~ z, ~ factor(bl), data = bldat)
```

I need feedback on the degrees of freedom difference as well as the `lm_lin` rescaling with singularities, which is a general problem for `lm_lin`.

**Comment by graemeblair** [comment]
if we have a block option in lm_lin, why don't we remove them in same way we remove for d-i-m? (I can imagine problems, but curious what you think those are)

**Comment by lukesonnet** [comment]
We don't have a block option in lm_lin, it's just another pre-treatment covariate. I'm not sure it makes sense to create a special machinery in the lm_lin estimator.

**Comment by graemeblair** [comment]
Ah sorry, my mistake

**Comment by graemeblair** [comment]
I'm not sure there is a solution here; really the user should drop those blocks before running `lm_lin`. Is there a sensible warning for singularities issues already?

**Comment by lukesonnet** [comment]
Yes, so I think we might just have to let it ride w/ those warnings being a caveat.

**Comment by lukesonnet** [comment]
Ok, this difference with lin currently exists and I think is totally fine. See #148 for this change.
