### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/estimatr#15]
The tests should verify for `lm_robust`, `lm_lin`, `difference_in_means`, and `iv_robust` that the following works:

(1) all combinations of weights, subsets, cluster variable, and block variable (if defined);
(2) faster than their base R equivalent with small data;
(3) faster than their base R equivalent with big data (something like 5000 observations?) -- this could have the flag not run on CRAN so that they are only run on our computers during testing;
(4) check against the answer for as many as possible;
(5) all outputs in all four functions have exact same column names.

**Comment by lukesonnet** [comment]
Also do some additional tests as mentioned in #23, which I will close and just leave linked here.

**Comment by lukesonnet** [comment]
These tests are done. Speed benchmarks are noted in the list to cran submission and a version of them is done.
