### ISSUE TITLE
add option to turn off variance calculations in difference_in_means

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/estimatr#152]
and in general allowing users to turn this off any time they just want estimates. for example for RI users.

**Comment by lukesonnet** [comment]
In `lm_robust` and iv and lin, users can use `se_type = "none"`.

For d-i-m and ht, I propose either `variance = TRUE` or `get_var = TRUE`

Thoughts?

**Comment by nfultz** [comment]
Why not `se_type = "none"` to match the other stuff?

**Comment by nfultz** [comment]
"default" ?
