### ISSUE TITLE
horvitz_thompson

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/estimatr#18]
We'd like to implement `horvitz_thompson` as a second estimator, mimicking the functionality of `difference_in_means`.

**Comment by lukesonnet** [comment]
I think a bit more guidance on this would be appreciated. I'm not sure how this would mimick the functionality of `difference_in_means` if it is primarily used to estimate totals. Do you think you could provide a reference that discusses the usage the way you would like it implemented?

Thank you. Also, an eventual question I think will appear later: for the estimate of the variance, should I by default assume that the weights/probabilities are known and fixed when passed by the user?

**Comment by lukesonnet** [comment]
Even an example of an application would likely be all I need; this isn't an estimator I'm familiar with.

**Comment by graemeblair** [comment]
It can be used as a drop-in replacement for `difference-in-means` for estimating the difference in means. I think the usage will be identical or nearly identical. The estimator for the totals can be divided by N to obtain the estimator for the mean. I think the discussion in the Imbens-Rubin book is good, but will check tomorrow when in the office.

Yes, you can assume that `Pr(T_i=1)` is fixed and known.

**Comment by lukesonnet** [comment]
Ok, just checked out Imbens-Rubin. I'll implement eqn 17.8 as the estimator, but IR aren't very clear about the variance.

Looking at the estimator of the variance proposed by Aronow and Middleton [here](http://aronow.research.yale.edu/unbiased.pdf), but not sure if that's the variance (eq 35) we want to use, It seems to be the most appropriate.

Another question: do we assume that joint probabilities are just the products of probabilities?

**Comment by graemeblair** [comment]
Great. Yes, that's the variance we want I think.

I'm not sure, remind me where that's relevant? I haven't worked through all this since last fall.

**Comment by acoppock** [comment]
The joint inclusion probabilities are the product of the marginal inclusion probabilities in simple, complete, and blocked designs (I *think* ????) but certainly not in clustered designs, since the joint inclusion probs for units in the same cluster is equal to the marginals in that case.

It’s probably worth writing to peter to get the code that generates table 2 from the data in table 1.

**Comment by lukesonnet** [comment]
Right, the only joint inclusion probs you need to calculate for clustered designs are cross-cluster, as you treat can clusters as one for the variance estimation (at least as far as I can tell from eqn 35).

I can't see how the join inclusion probability = product of marginals is true in blocked designs, well at least in pair-matched designs.

I was also going to suggest writing to Peter. Who should?

Re: timeline, this looks less promising unless we get a quick reply, you think I should just go ahead myself (which I can if I'm reading the eqn correctly, I can benchmark using this table).

**Comment by lukesonnet** [comment]
@graemeblair, the joint inclusion probabilities are anything in eqn35 where you see \pi_{1k1l}, which would be the joint inclusion probability for cluster k and cluster l in treatment condition 1.

**Comment by graemeblair** [comment]
Got it. Thanks. Luke, suggest you write to Peter explaining what you're coding up.

**Comment by lukesonnet** [comment]
https://github.com/ck37/htestimate

Software for estimators discussed in Aronow + Middelton.

**Comment by lukesonnet** [comment]
Implemented for simple and clustered designs. Would love to have standard analysis code to benchmark this against, and I can't find any myself, much to my surprise.

**Comment by graemeblair** [comment]
Macartan suggests re benchmarking: HT should perform the same as d-i-m whenever the number of units to be selected is fixed within every group that are assigned with a given probability. For example if there are 2 units to be assigned with probability .5 and exactly one is selected.  So for many standard designs with fixed numbers chosen from blocks and homogeneous probabilities within blocks you can check that the results are the same.

**Comment by lukesonnet** [comment]
Thanks Graeme. I can do this, but I'm guessing this only applies to the
estimates themselves and not the uncertainty around the estimates. Is this
true? Either way, I'll check both.

Luke Sonnet
PhD Student, Political Science
UCLA

**Comment by acoppock** [comment]
at a minimum, I want to know if the two estimates of uncertainty differ.  My intuition is that if they differ, one must be wrong.  or maybe they make different assumptions? I think we might need to do some more testing, then maybe ask joel or peter….

**Comment by lukesonnet** [comment]
Well it's likely the horvitz-thompson estimator. Anyways, the `luke-ht` branch has the latest implementation of the HT estimator. Maybe 

The variance of the HT estimator is greater than that of the DIM in this very simple case:

```
  n <- 100
  dat <- data.frame(y0 = rnorm(n),
                    z = rep(0:1, each = n/2),
                    ps = rep(0.5, n))

  dat$y1 <- dat$y0 + 0.43
  dat$y <- ifelse(dat$z, dat$y1, dat$y0)

  horvitz_thompson(y ~ z,
                   ps,
                   data = dat)
  difference_in_means(y ~ z,
                      data = dat)
```

```
> horvitz_thompson(y ~ z,
+                  ps,
+                  data = dat)
  coefficient_name       est        se          p    ci_lower ci_upper df
1                z 0.3127297 0.1750753 0.07714997 -0.03470152 0.660161 98
> difference_in_means(y ~ z,
+                     data = dat)
  coefficient_name       est        se          p    ci_lower  ci_upper df
1                z 0.3127297 0.1722365 0.07247438 -0.02906795 0.6545274 98
```

The variance for the HT is the following, where `Y1` and `Y2` are already weighted, ie. `Y1 = Y[condition == 1] / ps[condition ==1]`:

```       
se <- 
  sqrt(
    (var_ht_total_no_cov(Y2, diag(ps2)) / length(Y2)^2 +
      var_ht_total_no_cov(Y1, diag(ps1)) / length(Y1)^2)
  )

# Variance of the total
var_ht_total_no_cov <-
  function(y, ps) {
    sum((1 - ps) * ps * y^2)
  }
```

This is just the sum of the two estimated mean variances. Each mean variance is simply:
```
sum((1 - ps) * ps * y^2) / N^2
```
This formula can be found all over the place (and is a simplification of the more complete variance formula for the special case where the joint inclusion probability == the product of the marginals for all pairs of observations, such as in this design).

The variance for the DIM is the following:
```
se <- sqrt(var(Y2) / length(Y2) + var(Y1) / length(Y1))
```

**Comment by lukesonnet** [comment]
I have implemented both the standard HT variance estimator, which I showed in the above comment, and a version that assumes constant effects following Peter's advice using a `constant_effects` boolean flag. The constant effects standard errors match what you get with [ck37/htestimate](https://github.com/ck37/htestimate), a package written by who I believe is a graduate student of Joel Middleton's.

However, in a toy example, this constant effects estimator appears to be biased downwards, although the standard estimator is somewhat conservative. I haven't tested more complicated examples for now. I'll paste this toy example.

I've also implemented what I believe is the appropriate SEs for clustered and blocked designs, although I don't have a good benchmark implementation for those. I'll keep looking and see if I can match [ck37/htestimate](https://github.com/ck37/htestimate) using a constant effects assumption for clustered designs.

#### Toy example of simple randomization and constant effects underestimating uncertainty

```
## Install from branch with ht estimator
devtools::install_github('DeclareDesign/estimatr', ref = 'luke-ht')
library(estimatr)
its <- 1000
n <- 1000

ht_ests <- dim_ests <-  numeric(its)
ses_constant_ht <- ses_ht <- ses_dim <- numeric(its)

for(i in 1:its) {
  
  ## DGP with truly random 0.5 chance for each unit being treated
  dat <-
    data.frame(
      p = 0.5,
      z = rbinom(n, 1, 0.5),
      y0 = rnorm(n, sd = 3)
    )
  
  ## Constant treatment effects
  dat$y1 <- dat$y0 + 3
  dat$y <- ifelse(dat$z, dat$y1, dat$y0)
  
  ht_ce <-
    horvitz_thompson(
      y ~ z,
      p,
      data = dat,
      constant_effects = T
    )
  
  ht <-
    horvitz_thompson(
      y ~ z,
      p,
      data = dat,
      constant_effects = F
    )
  
  dim <- difference_in_means(y ~ z, data = dat)
  
  ht_ests[i] <- ht_ce$est
  dim_ests[i] <- dim$est
  ses_ht[i] <- ht$se
  ses_constant_ht[i] <- ht_ce$se
  ses_dim[i] <- dim$se
  
  if (i %% 50 == 0) print(i)
}

# sd of sampling dist
sd(ht_ests)
# mean of estimated ses
mean(ses_ht)
mean(ses_constant_ht)

# sd of sampling dist for DIM
sd(dim_ests)
# mean of estimated ses
mean(ses_dim)
```

**Comment by ck37** [comment]
Yes, I worked with Joel on htestimate.

**Comment by acoppock** [comment]
Just worked through this example, which is worrying.  Chris, have you guys come across this downward bias under the constant effects assumption?

**Comment by ck37** [comment]
I have not investigated it myself (these days I'm doing primarily targeted learning) but looping in @joelmidd; might also want to send Joel an email. All of our automated tests are at https://github.com/ck37/htestimate/blob/master/tests/testthat/testHtEstimate.R

**Comment by lukesonnet** [comment]
You can replicate the SEs you get with `estimatr` in the htestimate package:

```
devtools::install_github('DeclareDesign/estimatr', ref = 'luke-ht')
devtools::install_github('ck37/htestimate')

n <- 100
## DGP with truly random 0.5 chance for each unit being treated
dat <-
  data.frame(
    p = 0.5,
    z = rbinom(n, 1, 0.5),
    y0 = rnorm(n, sd = 3)
  )
## Constant treatment effects
dat$y1 <- dat$y0 + 3
dat$y <- ifelse(dat$z, dat$y1, dat$y0)

## hack to build prob matrix with all 0.5 incl. probs and 0.25 joint incl. probs
assignments <- matrix(rbinom(n*10000, 1, pr = 0.5), nrow = n)
prob_matrix <- htestimate::createProbMatrix(assignments)
prob_matrix
prob_matrix[prob_matrix < 0.35 & prob_matrix > 0.15] <- 0.25
prob_matrix[prob_matrix < 0.6 & prob_matrix > 0.4] <- 0.5
table(diag(prob_matrix))
htestimate::htestimate(dat$y,
                       as.factor(dat$z),
                       c(1, -1),
                       prob_matrix,
                       approx = 'constant effects')
estimatr::horvitz_thompson(y~z,
                           p,
                           data = dat,
                           constant_effects = T)
```

**Comment by lukesonnet** [comment]
I've implemented the ability to learn simple or completed random assignment from a declaration by `randomizr::declare_ra()` in `horvitz_thompson` (blocked and clustered forthcoming).

Again, the simple ht estimator, which does not make the constant effects assumption but rather only gets the variances of the totals for Y0 and Y1 (which is much more complicated to implement with  complete random assignment), is much better wrt coverage. See the extension of the above here:

```r
## Install from branch with ht estimator
devtools::install_github('DeclareDesign/randomizr')
devtools::install_github('DeclareDesign/estimatr', ref = 'luke-ht')
library(estimatr)
its <- 100
n <- 100

ht_ests <- ht_comp_ests <- dim_ests <-  numeric(its)
ses_constant_ht <- ses_ht <-ses_comp_constant_ht <- ses_comp_ht <- ses_dim <- numeric(its)

for(i in 1:its) {

  ## DGP with truly random 0.5 chance for each unit being treated
  dat <-
    data.frame(
      p = 0.5,
      z = rbinom(n, 1, 0.5),
      y0 = rnorm(n, sd = 3)
    )

  ## Constant treatment effects, SRS
  dat$y1 <- dat$y0 + 3
  dat$y <- ifelse(dat$z, dat$y1, dat$y0)

  decl_simp <- randomizr::declare_ra(N = n, simple = T)

  ht_ce <-
    horvitz_thompson(
      y ~ z,
      data = dat,
      constant_effects = T,
      declaration = decl_simp
    )

  ht <-
    horvitz_thompson(
      y ~ z,
      data = dat,
      declaration = decl_simp
    )

  ht_ests[i] <- ht_ce$est
  ses_ht[i] <- ht$se
  ses_constant_ht[i] <- ht_ce$se

  dat$z <- sample(rep(0:1, each = n/2))
  decl_comp <- randomizr::declare_ra(N = n, simple = F)
  ## Constant treatment effects, CRS
  dat$y1 <- dat$y0 + 3
  dat$y <- ifelse(dat$z, dat$y1, dat$y0)
  ht_ce <-
    horvitz_thompson(
      y ~ z,
      data = dat,
      constant_effects = T,
      declaration = decl_comp
    )

  ht <-
    horvitz_thompson(
      y ~ z,
      data = dat,
      declaration = decl_comp
    )
  dim <- difference_in_means(y ~ z, data = dat)

  ht_comp_ests[i] <- ht_ce$est
  ses_comp_ht[i] <- ht$se
  ses_comp_constant_ht[i] <- ht_ce$se

  dim_ests[i] <- dim$est
  ses_dim[i] <- dim$se

  if (i %% 5== 0) print(i)
}

# sd of sampling dist
sd(ht_ests)
# mean of estimated ses
mean(ses_ht)
mean(ses_constant_ht)

# sd of sampling dist
sd(ht_comp_ests)
# mean of estimated ses
mean(ses_comp_ht)
mean(ses_comp_constant_ht)
```

This is kind of slow right now, but I'll work on speeding it up.

**Comment by lukesonnet** [comment]
Macartan points out that HT should work even without variation in treatment. The following both need to work:

```
# One obs
ht_data = data.frame(y = 1, z = 1, p = .5)
horvitz_thompson(y ~ z, data = ht_data, condition_prs = p)
# Only one treatment within each block
ht_data = data.frame(y = rnorm(6), z = c(0:1), j = rep(1:2, each = 3), p = .5)
horvitz_thompson(y ~ z, data = ht_data, blocks = j, condition_prs = p)
# Only one treated and one control in each block
ht_data = data.frame(y = rnorm(4), z = c(0:1), j = rep(1:2, each = 2), p = .5)
horvitz_thompson(y ~ z, data = ht_data, blocks = j, condition_prs = p)
```

None of them work right now. I have to change that.

**Comment by lukesonnet** [comment]
As stated in Slack, here's where we stand:

Using Joel Middleton's code I dug up, I was able to check our standard errors in some simple cases. Basically, we have the following situation:

(A) our “youngs” inequality standard error estimator (the conservative one) is right, and we match the estimate and standard error for simple randomized designs with this young’s SE that joel gets
(B) Joel appears to be building the condition_pr_mat incorrectly for complete randomized case. In any case, if I use his pr mat and pass it to our function, we get the same young’s inequality standard error for the complete randomized case.
(C) our “constant” effects assumption SE seems to be a bit off. A sign is different in our formula than from what I think it should be from the lit, but it currently is correct for the case where `horvitz_thompson()` only uses the marginal condition probabilities (i.e. simple randomized design).

The gist: I’m happy shipping with only young’s inequality or maybe young's inequality + constant effects SEs for simple randomized designs because I'm pretty sure their both right. However, I'm not sure I'm happy relying on (B) being correct, because that means Joel made the mistake instead of me, which is unlikely. Nonetheless I can't find my error.

**Comment by lukesonnet** [comment]
Also, thanks to @jaspercooper's run-through, I've noticed that DeclareDesign will give you Z_cond_prob which appears to be the probability of unit i being in its assigned condition.

Horvitz-Thompson really wants condition2_pr. I will probably rename, but could someone confirm that is what DD does?

**Comment by acoppock** [comment]
`condition_pr` ok with me

**Comment by lukesonnet** [comment]
We've kept it as `condition_prs`. 

We only have "constant" for simple randomized cases. We force collapsed version of the Young's inequality variance if we can learn the design is clustered, and we treat each unit as its own cluster and use the same equation for Young's variance if we are unaware if the design is clustered.

**Comment by lukesonnet** [comment]
Closing this and opening more pointed tickets.
