### ISSUE TITLE
benchmarking

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/estimatr#19]
Testing/benchmarking: for a 10-unit experiment, can you show in a test that various designs (as many as you can think of) are unbiased for the true SATE? You could start with one or two to get us started.

Since there are only 252 ways to assign 5 of 10 units to treatment (you can get them all from `randomizr::obtain_permutation_matrix`) this shouldn't be too expensive in terms of computation time.  Make really heterogeneous and weird potential outcomes, then loop or apply through a function that reveals outcomes, runs the estimators and records the output.

**Comment by lukesonnet** [comment]
Added tests for estimated ATE for following designs:

- Complete randomization
- Block randomization, 2x5
- Matched pair, 5x2
- Clustered, 5 clusters of size 2
- Matched pair clustered, 3 blocks, of sizes 4, 4, 2, with clusters of size 2 in the first two blocks and size 1 in third block.

Average of estimates across all permutations for those designs equals the true SATE. Works for POs I have hardcoded, also works for more standard draw of POs from `rnorm`, but those aren't included in the tests.

**Comment by lukesonnet** [comment]
Ah, one problem with these tests. They won't work with the CRAN version of `randomizr` because it now depends on it for the permutation matrix which is only in the github version of `randomizr`. Not sure how that affects the submission.

**Comment by graemeblair** [comment]
Thanks, good pointer. Let's think about this at submit time.

**Comment by lukesonnet** [comment]
Unless `randomizr` with that function gets on CRAN before we submit `estimatr`, unit tests will fail, as they are doing now in all of the checks that are set up.

**Comment by graemeblair** [comment]
Thanks, yeah we would submit `randomizr` before if needed. We can also use skip_on_cran() in testthat if we can't do that, which forces the tests to run only on your computer not on CRAN.

**Comment by acoppock** [comment]
we can get rid of the randomizr dependency by enumerating all possible random assignments with code like this:

```combn(10, 5, tabulate, nbins = 10)```

(that produces 252 treat 5 of 10 complete ras)  

Slightly hairier for clustered and blocked designs because of merging, etc. 

We could also mark the permuatation tests as "not on cran"

**Comment by lukesonnet** [comment]
I'm going to actually comment out the randomizr one for now, until the new randomizr is on CRAN. The test it is used for is to show that the DIM is unbiased. I hope to do nothing to break that, and can manually run the test on my machine until randomizr is up. This should mean all the CI stuff here on github will finally work.

As for future benchmarking, we also want:

* Speed and answers versus clubSandwich
* Speed and answers versus Stata

These probably won't be tests as they won't run but could be demos? @nfultz, are demos the place to put something that relies on another package without adding it to `Suggests:`? Is there such a place?

**Comment by lukesonnet** [comment]
All of the above is implemented and now that `randomizr` is on CRAN they are all running.
