### ISSUE TITLE
docs error on HT

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/estimatr#194]
```term | estimate | std.error | p.value | ci.lower | ci.upper | df | outcome
-- | -- | -- | -- | -- | -- | -- | --
z_clust | NA | NA | NA | NA | NA | NA | y_clust```

http://estimatr.declaredesign.org/articles/getting-started.html#horvitz_thompson

**Comment by lukesonnet** [comment]
This happens because my rewrite of `clean_model_data.R` clobbered a `droplevels` and so the tapply of cluster-wise totals had NAs in it for clusters it looked for in the treatment group. Solving this now.

**Comment by lukesonnet** [comment]
Actually, this was the result of the `randomizr` rewrite; I misdiagnosed why it was still a factor.

This dredged up some other changes that were necessitated by the `randomizr` rewrite that I had missed, as well as some tests that were wrong.
