### ISSUE TITLE
Support for varying probabilities when simple=TRUE 

### ISSUE THREAD

**Issue by nfultz** [DeclareDesign/estimatr#200]
The next version of randomizr will allow varying probabilities when simple = TRUE - we should check if there is anything assuming that the probabilities are constant.

**Comment by macartan** [comment]
related? I am getting error:

> complete_ra(10)
Error in .Call("randomizr_vsample", pmat, PACKAGE = "randomizr") :
  "randomizr_vsample" not available for .Call() for package "randomizr"

error inherited by declare_assignment

**Comment by nfultz** [comment]
Moving that to randomizr https://github.com/DeclareDesign/randomizr/issues/63
