### ISSUE TITLE
HT warning 

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/estimatr#210]
Receiving these warnings:
```
Assuming complete random assignment of clusters within blocks. User can use `ra_declaration` or `condition_pr_mat` to have full control over the design.
```
even though blocks are specified (and simple = FALSE provided)

**Comment by graemeblair** [comment]
Could you share an example?

**Comment by macartan** [comment]
b <- .4
p <- c(.5, .7, .9)   # block assignment probabilities
# Model ------------------------------------------------------------------------
U <- declare_population(
  block = add_level(N = 3,   u = 1:3, prob = p),
  indiv = add_level(N = c(100,200, 300),
                    e0 = u + rnorm(N),
                    e1 = u + rnorm(N)))

Y <- declare_potential_outcomes(Y_Z_0 = e0,
                                Y_Z_1 = e1 + 2*b*(block == "1") +
b*(block == "2"))
# Inquiry ----------------------------------------------------------------------
Q <- declare_estimand(ATE = mean(Y_Z_1 - Y_Z_0))
# Data Strategy ----------------------------------------------------------------
Z <- declare_assignment(blocks = block, block_prob = p)
R <- declare_reveal()
# Answer Strategy --------------------------------------------------------------
A7 <- declare_estimator(Y ~ Z, estimand = Q, blocks = block, simple = FALSE,
                        model = horvitz_thompson, condition_prs = prob,
                        label = "Horvitz-Thompson")

# Design -----------------------------------------------------------------------

design <- U/Y/Z/Q/R/A7


diagnose_design(design, sims = 2)


## Assuming complete random assignment of clusters within blocks. User
can use `ra_declaration` or `condition_pr_mat` to have full control
over the design.
## Assuming complete random assignment of clusters within blocks. User
can use `ra_declaration` or `condition_pr_mat` to have full control
over the design.
