### ISSUE TITLE
Fix dependency issue from CRAN

### ISSUE THREAD

**Issue by lukesonnet** [DeclareDesign/estimatr#211]
From CRAN:

These seem to have undeclared package dependencies in their unit test
code (R files in tests subdirs), see below.

Can you pls fix as necessary?  (Add the missing package dependencies to
Suggests, I guess.)

Please note that these issues are currently not yet detected by the CRAN
incoming (or regular) checks.

Best
-k

```
'::' or ':::' import not declared from: ‘clubSandwich’
'library' or 'require' call not declared from: ‘ivpack’
```

**Comment by nfultz** [comment]
Definitely replace the `library("ivpack")` with `ivpack::ivreg` as we
generally do not want to modify the search path from a unit test, which can
cause idempotency issues. Also add skip_if_cran to that test if the intent
is to not Suggest them.

**Comment by lukesonnet** [comment]
There seems like no way to solve this without adding suggests. Our hack of "skip_if_not_installed" no longer seems to be accepted by CRAN if they are going to complain about this.

The only alternative I see now is using .Rbuildignore?

**Comment by nfultz** [comment]
skip_if_cran should still be OK though ? :confused:

**Comment by lukesonnet** [comment]
Yes I think so, sorry. I'm just trying to get rid of all of the `library` calls, but that seems unnecessary.

**Comment by lukesonnet** [comment]
I don't think skip_if_cran will work, but if not we can always split them out and .Rbuildignore them.

**Comment by lukesonnet** [comment]
Closing this unless we get another warning from CRAN...
