### ISSUE TITLE
blocks in lm_robust

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/estimatr#212]
It would be useful if lm_robust could take a blocks argument so that input is similar to d-i-m;

* I suppose until there is an absorb/felm  approach this would be essentially adding as.factor(block) to the formula. 
* A complication though is that block variables may only have one block in applications (this is the default in block_and_cluster_designer) in which case as.factor() breaks

**Comment by lukesonnet** [comment]
Hi Macartan,

I've spent the last three works doing no other DD work other than trying to get `fixed_effects` working as an option. Once that PR is finally finished, I'll be sure to write a short vignette about how to do it (and some pitfalls in using it that I've been unable to avoid).

It has huge speed gains for designs such as matched-pairs (or whenever there are many blocks) when using HC1 standard errors, but I'm just trying to make sure it all works nicely right now.

**Comment by macartan** [comment]
Sounds really great

**Comment by macartan** [comment]
allowing either specification sounds good

**Comment by macartan** [comment]
Can we handle single block case?: This is relevant for a vignette in which the number of blocks varies; nice to be able to handle the single block case without changing structure of code.  

```
df <- draw_data(block_cluster_two_arm_design)

> lm_robust(Y~Z, data = df, fixed_effects = ~ blocks)
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels
```

**Comment by lukesonnet** [comment]
Yes, I can fix this to specially handle the single block case. I will hopefully add this later in the week, but can't get to it until ~Wednesday.
