### ISSUE TITLE
Stacking coefficients w/ interactions in lm_robust

### ISSUE THREAD

**Issue by garethnellis** [DeclareDesign/estimatr#217]
```
df <- fabricate(
  block = add_level(N = 10),
  ind = add_level(N = 4, Y = rnorm(N), Z = complete_ra(N), X = complete_ra(N))
)

lm_robust(Y ~ Z*X + as.factor(block), data = df)
```
interaction coefficients printed at very bottom; can they be stacked so as to be in 3rd position (as in lm, felm etc)? easier to grab from when iterating.

**Comment by lukesonnet** [comment]
`lm` also puts them at the bottom unless you precompute the interaction.

In any case, why don't you install from github and try this out:
```
df <- fabricate(
  block = add_level(N = 10),
  ind = add_level(N = 4, Y = rnorm(N), Z = complete_ra(N), X = complete_ra(N))
)

lm_robust(Y ~ Z*X, fixed_effects = ~ block, data = df)
```

Will be faster with large enough number of blocks or with HC1 errors.
