### ISSUE TITLE
variable_names -> coefficient_name

### ISSUE THREAD

**Issue by acoppock** [DeclareDesign/estimatr#22]
In all the return objects from d-i-m and lm_robust etc., 
- [x] the return frame should have a column named "coefficient_name" rather than the current "variable_names"
- [x] right before returning, it should clobber the row names of the return frame via `rownames(obj) <- NULL`

**Comment by graemeblair** [comment]
can this be closed, @lukesonnet?

**Comment by lukesonnet** [comment]
Yeah it's committed and will be added to the lm_lin pr which I'll push in <20 minutes with the Lin replication
