### ISSUE TITLE
benchmarking clustered SEs

### ISSUE THREAD

**Issue by acoppock** [DeclareDesign/estimatr#23]
Not sure where we are on benchmarking our clustered standard errors.  But it would be great to test against stata?

I also came across this http://rforpublichealth.blogspot.com/2014/10/easy-clustered-standard-errors-in-r.html

which summarizes the main ways that ppl currently do clustered SEs in R.

**Comment by lukesonnet** [comment]
Thanks for this. Currently we match the SEs with BMlmSE.R that was linked in the Green Lab SOP. That produces the CR2 ses and the Stata ses and we match.

I'll check this post and I just read through the clubSandwich paper and was going to implement it for WLS

**Comment by acoppock** [comment]
tremendous, thanks!

**Comment by lukesonnet** [comment]
One thing the clubSandwich paper points out is that with fixed effects (and clusters that don't vary within fixed effects), there is no solution to the matrix used by BM for the adjustment. They generalize and provide a solution. I've had this problem trying to apply the BM ses to my own work and I've had to use the Stata SEs.

So I think we should default to the clubSandwich version, but I'll test speed and reliability before doing that.

**Comment by acoppock** [comment]
When you say “fixed effects” do you mean any categorical covariate?

Does the BM adjustment not work when you include, for example, a dummy for female?

Regardless of the answer to the above, sounds like the clubSandwich default is worth exploring.

**Comment by lukesonnet** [comment]
No. The reason I say fixed effects is because that is the focus of the discussion in the clubSandwich paper. They just say that:

> for some ﬁxed eﬀects models that are common in economic applications, Equation 5 [BM adjustment] has no solution. Angrist and Pischke (2009) note that this problem occurs in balanced state-by-year panel models that include ﬁxed eﬀects for states and for years, where (I - X_j (XtX)^-1 t(X_j)) is not of full rank. Young (2016) reported that this problem occurred frequently when applying BRL to a large corpus of ﬁtted regression models drawn from published studies."

They don't give more information about how or why that will happen, but I suspect it has to do with how clusters nest within sets of categorical variables. Honestly I'm just guessing about that, but I noticed this in an experiment I was trying to analyze with our package (BM errors failed, Stata errors worked fine).

**Comment by lukesonnet** [comment]
Linking this in #15 and closing.
