### ISSUE TITLE
lm_lin busted if covariate is constant

### ISSUE THREAD

**Issue by acoppock** [DeclareDesign/estimatr#248]
Or at least I think that's part of the problem:

```
library(DeclareDesign)

dat <-
  fabricate(
    N = 100,
    Y = rnorm(N),
    Z = complete_ra(N),
    X_num = 4,
    X_char = "four",
    X_fac = factor(4)
  )

# no error
lm_lin(Y ~ Z, covariates = ~ X_num, data = dat)
# error
lm_lin(Y ~ Z, covariates = ~ X_char, data = dat)
# error
lm_lin(Y ~ Z, covariates = ~ X_fac, data = dat)
```

**Comment by lukesonnet** [comment]
Alex,

This is probably the preferred behavior. See the errors in the following for example:

```
lm(Y ~ X_char, data = dat)
lm(Y ~ X_fac, data = dat)
```

I don't really want to override the nice R model matrix building we are using to allow these to work, but I probably could.

**Comment by lukesonnet** [comment]
I will close this issue next Monday absent insistence that we support this, as it requires writing a custom `model.matrix` function or additional preprocessing that will slow down other implementations.
