### ISSUE TITLE
Fix segfault issue in demeanMat

### ISSUE THREAD

**Issue by lukesonnet** [DeclareDesign/estimatr#268]
This error comes up during a couple calls to `demeanMat` on Solaris (https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/estimatr-00check.html).

Seems to mostly be triggered by `iv_robust()`.

**Comment by graemeblair** [comment]
Also triggered in DesignLibrary tests on Solaris https://cran.r-project.org/web/checks/check_results_DesignLibrary.html

**Comment by lukesonnet** [comment]
Thanks, has CRAN issued a deadline on this?

**Comment by graemeblair** [comment]
I don't think it's a problem at the moment - only when we resubmit any of these

**Comment by lukesonnet** [comment]
I can replicate this on rhub's solaris box. Trying to fix now.

**Comment by nfultz** [comment]
Solaris likely has a different C++ std library, compiler and compiler flags - so I would generally not trust it to do the same as gcc.

This is the block in question, that your referenced:

```
for (int i=0; i<fe.size(); i++) {
    std::string fei = Rcpp::as<std::string>(fe(i));
    Eigen::Array2d dat;
    dat(0) = weights(i) * x(i);
    dat(1) = weights(i);
    if (sums.find(fei) != sums.end()) {
      sums[fei] += dat;
    } else {
      sums[fei] = dat;
    }
  }
```



Here, `dat` is declared on the stack, and can be deallocated as soon as the compiler thinks it has gone out of scope. This _could_ be as early as the end of the block for the loop (I am reading between the lines here https://www.oreilly.com/library/view/practical-c-programming/0596004192/ch09.html) - then at the next loop, `sums[fei]` is in the map, but points to an object that no longer exists.

But I'm speculating, haven't worked with this stuff in a while.

**Comment by lukesonnet** [comment]
Thank you for your assistance. I'll use this when dig back in.

**Comment by nfultz** [comment]
This would also be a good one to ask about on the Rcpp mailing list.

**Comment by lukesonnet** [comment]
I guess it depends on how it's passing it to `sums[fei]`. Exploring this now.
