### ISSUE TITLE
my matrix is too large!

### ISSUE THREAD

**Issue by acoppock** [DeclareDesign/estimatr#27]
```
df <- data.frame(Y = rnorm(100), Z = rbinom(100, 1, .5), X = rnorm(100), W = runif(100))
lm_robust(Y ~ Z, data = df)
```
```
error: Mat::init(): requested size is too large
 Error in lm_robust_helper(y = y, X = design_matrix, cluster = cluster,  : 
  Mat::init(): requested size is too large 
```

https://media.giphy.com/media/EYJjKIDi5FKEg/giphy.gif

(this is from the tests...)

**Comment by lukesonnet** [comment]
That's both a dark reference and a bug that I cannot recreate.

**Comment by lukesonnet** [comment]
And I'm not seeing it in the linux or mac tests on Travis CI.

Hate to be that guy, but can you try removing the package and then reinstalling it?

**Comment by acoppock** [comment]
Ok something is weird, maybe with branches.  When I do ```devtools::install_github("DeclareDesign/estimatr")``` it works fine.  When I rebuild based on the master branch from github, i get the error again.

**Comment by lukesonnet** [comment]
my guess is that you have a custom set of commands for your compiler that are overriding the defaults set by the package (and thus aren't using C++11 or something like that). What are doing to install from the code yourself?

**Comment by acoppock** [comment]
I used rstudio's build and reload command.

**Comment by lukesonnet** [comment]
Can you try devtools::install() instead? All three of these options work on my machine.

**Comment by acoppock** [comment]
> devtools::install()
Installing estimatr
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/Users/Alex/git_projects/estimatr' --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *source* package ‘estimatr’ ...
** libs
make: Nothing to be done for `all'.
installing to /Library/Frameworks/R.framework/Versions/3.4/Resources/library/estimatr/libs
** R
** data
*** moving datasets to lazyload DB
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (estimatr)
Reloading installed estimatr
> df <- data.frame(Y = rnorm(100), Z = rbinom(100, 1, .5), X = rnorm(100), W = runif(100))
> lm_robust(Y ~ Z, data = df)

error: Mat::init(): requested size is too large
 Show Traceback
 
 Rerun with Debug
 Error in lm_robust_helper(y = y, X = design_matrix, cluster = cluster,  : 
  Mat::init(): requested size is too large

**Comment by lukesonnet** [comment]
Ok so this line:
``` 
make: Nothing to be done for `all'.
```
Is saying that it is not actually recompiling the C++ code. When installing from online it must not be able to check whether there is already a compiled version of the code before installing and so it recompiles automatically. If you delete any files under `/src` that end in `.dll` or `.o` and rerun devtools;:install() what do you get?

**Comment by lukesonnet** [comment]
You can also force recompiling by trying `devtools::install('.', local = F)`

If these don't solve the problem, then something weird is going on that I'm unfamiliar with and we need to get some platform where I can debug this problem.

If these do solve the problem, then this means that we need to figure out how to force recompile under certain circumstances, or check when things aren't compiled correctly. I don't currently know how to do this. Of course, this problem won't exist for the vast majority of users as they will be installing off of GitHub or CRAN which will force recompilation, I believe.

**Comment by acoppock** [comment]
Ok great sleuthing: 

> devtools::install('.', local = F)
Installing estimatr
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD build  \
  '/Users/Alex/git_projects/estimatr' --no-resave-data --no-manual --no-build-vignettes 

* checking for file ‘/Users/Alex/git_projects/estimatr/DESCRIPTION’ ... OK
* preparing ‘estimatr’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* looking to see if a ‘data/datalist’ file should be added
* building ‘estimatr_1.0.tar.gz’

'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/ww/y3qvjm4d6gg9q0ymwz5vw5yh0000gn/T/RtmpMYWpJM/estimatr_1.0.tar.gz'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests 

* installing *source* package ‘estimatr’ ...
** libs
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -DARMA_64BIT_WORD=1 -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I/usr/local/include   -fPIC  -Wall -g -O2 -c RcppExports.cpp -o RcppExports.o
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -DARMA_64BIT_WORD=1 -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I/usr/local/include   -fPIC  -Wall -g -O2 -c lm_robust_helper.cpp -o lm_robust_helper.o
clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o estimatr.so RcppExports.o lm_robust_helper.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.4/Resources/library/estimatr/libs
** R
** data
*** moving datasets to lazyload DB
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (estimatr)
Reloading installed estimatr
> df <- data.frame(Y = rnorm(100), Z = rbinom(100, 1, .5), X = rnorm(100), W = runif(100))
> lm_robust(Y ~ Z, data = df)
  coefficient_name        est        se         p   ci_lower  ci_upper df
1      (Intercept)  0.1467338 0.1581050 0.3556470 -0.1670203 0.4604880 98
2                Z -0.0554685 0.2052721 0.7875598 -0.4628244 0.3518874 98

**Comment by lukesonnet** [comment]
Okay, then this is just a matter of compiled code lying around and RStudio/devtools not recognizing it needs to recompile because something has changed. It doesn't realize something has changed because all that changed are the options to be passed to the compiler rather than the source code itself. For example, the files need to be compiled with these flags to take advantage of the larger word size:
```
 -std=gnu++11
 -DARMA_64BIT_WORD=1
```

I think that if this is a problem it will be an edge case for a user who should be able to figure it out/its quick to solve and is not in our purview to change. This is an RStudio issue, I think.

Closing this. Feel free to disagree.
