### ISSUE TITLE
getting started in README

### ISSUE THREAD

**Issue by shuckle16** [DeclareDesign/estimatr#273]
Hi, thanks for working on such a cool package! I'm looking forward to using it. It seems the Getting Started links in the README are giving 404's, though.

**Comment by lukesonnet** [comment]
Thanks for this. Will resolve ASAP.

For now please see: https://declaredesign.org/r/estimatr/

**Comment by lukesonnet** [comment]
I'm going to hardcode all URLs to the declaredesign.org/r/estimatr website.
