### ISSUE TITLE
Transition to outputting "model fits" and building S3 methods

### ISSUE THREAD

**Issue by lukesonnet** [DeclareDesign/estimatr#28]
There should be a suite of classes named after the estimators that created them:

- horvitz_thompson
- difference_in_means
- lm_robust

Each of these should have their own s3 methods for:

- summary
- print
- coef
- vcov
- confint
- tidy
- predict (only for lm_robust? Actually I think we need a separate lm_lin class so we know to construct the centered and interacted data.)

Also Alex asked about anova, plot, and residuals. I think no on these, except maybe residuals on lm_robust?

Thoughts from alex that I didn't incorporate into the above:

We discussed this week that lm_robust should return a “model fit”. Normal model fits appear to be extremely heavy objects. lm fits store the data!

The value probably has to be a list (though we could have this be a dataframe with a vcov attribute!)
I don’t think we want to ape lm like syntax with summary(robust_fit)$coefficients.
I think that all computations on the data should be done when the model fit is created. Though I admit that this intuition is just coming from my aversion to carrying around the data, which seems computationally expensive.
> Luke: how expensive this is remains a ram vs. cpu problem, I'm not convinced it will be that expensive but I'll try and avoid it.

I’d also love it if the outputs of difference_in_means, horvitz_thompson and lm_robust were all unified somehow. Maybe they all have to be lists.
> Luke: I think they all have to be lists, but they can be similarly structured lists and `tidy()` will return that data frame we have always wanted <3

I think it would behoove us to take a peek around at other modelling functions in R (I guess those handled by stargazer is a good list?) and try to understand the variation in “model objects.” Maybe inspection of the broom package would also lead us in the right direction.

**Comment by graemeblair** [comment]
To me the important thing is that all those s3 methods work, not that it exactly looks like an lm fit object. So avoiding summary(fit)$coefficients etc. seems reasonable -- you can get the coefficients from coef(). Let's do what is fast and simple s.t. the s3 methods still work. 

I agree it would be nice if all the functions outputs were similar; I think lists are ok if needed given now we're making it easy to interact with the outputs through s3 methods and especially `tidy()`. Is there any trickiness you're thinking of?

Looking at broom seems great. Happy to have a Skype discussion on this after you take a look if useful.

**Comment by lukesonnet** [comment]
From Alex in #31:

> I think they [print and summary] should probably be the same as
> tidy(fit)
> for right now.
> 
> am I right in thinking that confint() and coef() methods are in the works too?

I agreed and will implement it this way. Should we add a print flag defaulting to FALSE in each of the estimator functions to determine whether to run print(obj) before returning the object?

**Comment by acoppock** [comment]
No, it should only print when called, i.e. Just like an lm object

**Comment by nfultz** [comment]
Might be overkill but also might be helpful: http://www.milbo.org/doc/modguide.pdf

I agree with about 90% of it.

**Comment by acoppock** [comment]
Wow, that is a useful document.

**Comment by lukesonnet** [comment]
I'll look through and implement that which is trivially a good idea. Some things may require us hanging on to more data and so we should discuss those.

**Comment by lukesonnet** [comment]
The next step here is to see how much saving y and or yhat for use in `predict` and `residuals` methods would hurt the diagnose command.

I will do this in `test-declare-design.R`

**Comment by lukesonnet** [comment]
Okay with PR #62, I think the only other S3 methods we should seriously consider are `residuals` and `weights`. Happy to add these if we don't mind adding objects of size `n`. I said earlier I would test this with diagnose, and I still will, but it's on the backburner.

One question though, @acoppock, about residuals and WLS. We currently compute y - XB for usage in vcov estimation, where y and X there have sqrt(weights) in them. That's because the variance estimators have the weight matrix sandwiched in the middle. However, these aren't the residuals we want to return, right?

We want y - XB, where y and X are in their original, unweighted form, because those are the actual residuals, correct?

**Comment by acoppock** [comment]
Yes that is correct (I believe!).

Estimation is weighted but prediction is not.

**Comment by lukesonnet** [comment]
Just noting here that our `tidy` method works without `broom` loaded and it works if `broom` is also loaded (before or after `estimatr`).

I imagine the only thing that would break this is if `broom` were to change the way the default S3 method, then whichever package is loaded first would break. I don't have a test for this because I don't think adding broom as a suggests is worth it, unless someone overrides me here.

**Comment by lukesonnet** [comment]
We now work with `broom` and most of these are estimated. Opening new issue for weights and residuals that I'm going to mark as post-CRAN because they involve adding size `n` objects and I think that we should only do that with more consideration.
