### ISSUE TITLE
add a "glance" method

### ISSUE THREAD

**Issue by acoppock** [DeclareDesign/estimatr#282]
Someone made a new regression output package built on the soon-to-be-released `gt` package. Estimatr isn't compatbile yet because we need a "glance" method:

> library(gtsummary)
> library(estimatr)
> 
> fit_1 <- lm_robust(mpg ~ hp, data = mtcars)
> fit_2 <- lm_robust(mpg ~ hp, se_type = "classical", data = mtcars)
> 
> gtsummary(list(fit_1, fit_2))
Error: No glance method for objects of class lm_robust

**Comment by graemeblair** [comment]
see https://github.com/vincentarelbundock/gtsummary/issues/8

**Comment by lukesonnet** [comment]
Will implement ASAP (hopefully today!)

**Comment by nfultz** [comment]
Extend via `generics`, same as broom - https://github.com/r-lib/generics/blob/master/R/glance.R

**Comment by lukesonnet** [comment]
Yep, thanks!

**Comment by lukesonnet** [comment]
Added glance for lm_robust and a Rbuildignored test for gt and gtsummary. Should I add iv_robust, and just present the second stage?

**Comment by lukesonnet** [comment]
Ok we don't return those but I'm happy to inplement them. That said we
still need to decide what goes into the main body. That's what I was asking
about.

Luke Sonnet
PhD Candidate, Political Science
UCLA

**Comment by graemeblair** [comment]
Sorry misunderstood, what's the main body? I thought it was one row with a set of model fit statistics.

**Comment by lukesonnet** [comment]
Ah yes. That's glance. I was thinking about gtsummary and the estimates and coefficients.

**Comment by lukesonnet** [comment]
Next step is to:

- mimic glance.ivreg and include standard IV metrics
- ensure that gtsummary takes the 2sls estimates in the main body
- I'll also try to do difference in means where it has basic metrics (including design type) in the glance

I'll try to do that today and then I'll open the PR.

**Comment by vincentarelbundock** [comment]
Funny. I came here to see if a `glance` had been requested before only to find that my specific issue was being discussed and worked on. Thanks, I appreciate it!

Let me know if there's anything I can do to help.

**Comment by lukesonnet** [comment]
Done in #285
