### ISSUE TITLE
rlang syntax not working as expected

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/estimatr#284]
In order to programmatically set the variables in formulae I thought you could do this:

```

df <- fabricate(N = 100, x = runif(N), Z = rbinom(N, 1, .5), y = Z*x + rnorm(N))

# works
lm_lin(y ~ Z, covariates = ~ x, data = df)

outcome_var = "y"
cov = "x"
tr = "Z"

# rlang syntax I thought should work
lm_lin(!!outcome_var ~ !!tr, covariates = ~ !!cov, data = a)
# Error in FUN(X[[i]], ...) : object 'outcome_var' not found
```

What am I missing? @nfultz @lukesonnet

**Comment by nfultz** [comment]
You don't need rlang here, you are just making a formula:

```
outcome_var = "y"
cov = "x"
tr = "Z"

f <- as.formula(paste(outcome_var, "~", tr))
g <- as.formula(paste("~", cov))

lm_lin(f, covariates = g, data = df)
```


Unclear if rlang splicing will work recursively inside formulas here:

https://github.com/DeclareDesign/estimatr/blob/master/R/estimatr_lm_robust.R#L227-L233

**Comment by lukesonnet** [comment]
I don't think I've ever used !! like this. Should it work?

**Comment by lukesonnet** [comment]
Is there an example of !! being used in formulae in other rlang friendly packages? An example could help me figure out if we can resolve this, but I'm unaware of any.

**Comment by acoppock** [comment]
I don't think we need to worry about this unless @graemeblair has a different view? I think NF's paste approach should solve most (all?) issues, no?

**Comment by graemeblair** [comment]
Will look around
