### ISSUE TITLE
Multiple-Test adjusted lh_robust comparisons?

### ISSUE THREAD

**Issue by DeFilippis** [DeclareDesign/estimatr#291]
Hey all, fantastic work with the new `lh_robust` command -- really loving it.  The one issue I have is that I'm wondering if it can be extended to perform simultaneous comparisons while adjusting for multiple-tests (such as in the multiComp package). 

I have a 4x2 experiment and want to be able to test to see if there are any differences between the treatment and the control on some factor that is four levels.   This yields 16 possible comparisons, but I want to adjust for multiple tests, and don't want to have to explicitly reference each of the tests.

Is this possible within the `lh_robust` framework?

**Comment by nfultz** [comment]
This is a good idea.

`lh_robust` is being backed by the `car` package, which doesn't have multiple testing adjustments as far as I know. Until it gets added there, or we implement it ourselves, you can fall back on the builtin `p.adjust` if you just need Bonferonni or BH.

@lukesonnet it would be easy to call p.adjust here - https://github.com/DeclareDesign/estimatr/blob/3cc4a071c6918aae8bf4de3fb851f6c30bc62c36/R/estimatr_lh_robust.R#L86

**Comment by DeFilippis** [comment]
Thanks for the quick reply.  What do you mean by the built-in "p.adjust?"  How would that work?

**Comment by acoppock** [comment]
R has a function called `p.adjust` where you can choose your correction, e.g, 

```
> p.adjust(c(0.01, 0.02, 0.04, 0.5, 0.79))
[1] 0.05 0.08 0.12 1.00 1.00
```

But I don't want to include such adjustments in estimatr, since it's hard to anticipate how many p.values are in a "family" together.  Better, I think, to induce users to adjust p.values manually so they can be explicit about what kinds of error they are defending against!

**Comment by lukesonnet** [comment]
Seeing as we don't do p.value adjustments anywhere in this package, I'd rather not build it in only here. It seems that our two overlords tend to agree, and so I'm closing this.

Thanks for the suggestion, @DeFilippis, but hopefully users can do this afterwards with `p.adjust()` and without much difficulty. I think given our ability to produce tidy data frames, people can `group_by()` outcomes, or treatments, or whatever their families are and then just apply `p.adjust()` to the relevant estimates post-estimatr.

I'll close this, although anyone can reopen it if they feel strongly.
