### ISSUE TITLE
better docs for na.omit behavior with multiple variables

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/estimatr#299]
When you do `lm_robust(cbind(Y1, Y2, Y3) ~ x, data = data)` vs `lm_robust(Y1 ~ x, data = data)` when there are missing values in Y2 and Y3 that are not missing in Y1, you get different answers for effect on `Y1`. This is also the `lm` behavior. It's not necessarily what you would expect so suggest a line in the docs on this.

**Comment by lukesonnet** [comment]
I will add something to the docs about this. However I do think this should be the expected behavior as you're just doing Y = XB

**Comment by graemeblair** [comment]
Thanks. That seems clear behind the scenes, but not necessarily to the user (plausible it could just be doing three regressions and stacking the results).

**Comment by acoppock** [comment]
seems easy enough to implement

**Comment by lukesonnet** [comment]
I don't really know the right place to put this, but I added it to `lm_robust()`. I think people doing multivariate regression should probably know this anyways but if you think it needs to be in a more visible place please advise.
