### ISSUE TITLE
Implement weighting with cluster-robust SEs

### ISSUE THREAD

**Issue by lukesonnet** [DeclareDesign/estimatr#3]
Check the R code here: https://github.com/jepusto/clubSandwich for how to implement the same small-sample correction for clustered errors with WLS.

**Comment by graemeblair** [comment]
Cool. @acoppock thoughts?

**Comment by acoppock** [comment]
Winston lin seyz:

I like the paper (Pustejovsky & Tipton) behind clubSandwich, but haven't tried the package. Seems worth a look …

Can we set up a Skype call to discuss pls?

Alex

**Comment by graemeblair** [comment]
Yes, pls set up. I'm on European time until Saturday.

**Comment by lukesonnet** [comment]
I'm in Pakistan until Friday then flying to California. Happy to meet most
Tu-Th mornings Eastern time.

Luke Sonnet
PhD Student, Political Science
UCLA

**Comment by lukesonnet** [comment]
Ok, I've implemented the `clubSandwich` estimator. Our package can produce the same SEs and degrees of freedom as the `clubSandwich` package.

It is a beast though, tons of calculations and matrices held in storage. It deserves some careful time reviewing the code for inefficiencies.

Next steps:
- Working on streamlining the code for this estimator
- Removing the BM estimator altogether (results are the same if `weights = 1`; will be removed if speed is better for new estimator)
- Documenting this estimator

**Comment by lukesonnet** [comment]
Note: still fails with a set of dummy variables capturing each of the clusters, the reason to implement clubSandwich (besides weighting). That's now top priority to fix.

**Comment by nfultz** [comment]
overall looks good so far. I don't really have a sense of how large of objects you are operating on though. 


 also I'd recommend keeping all the debugging output, but wrapping it in an appropriate debug macro, that way it's easy to compile it back in when you want it.

**Comment by graemeblair** [comment]
Thanks, Luke.

Could you say more about the debugging, Neal?

**Comment by lukesonnet** [comment]
OK, the new estimator is faster as is than BM and provides equivalent results, so I'm cutting out the old implementation of BM altogether.

**Comment by nfultz** [comment]
Sure, here is the debugging macro I've used:
https://github.com/nfultz/grpc/blob/master/src/common.h

Basically, you uncomment one line, recompile, and the logging is on, otherwise the macro evaluates to a blank. I stole the idiom from the `RProtobuf` package.

**Comment by lukesonnet** [comment]
There are many arrays where one or more of the dimensions is `k`, where `k` is the rank of the design matrix. So when including a large number of covariates, in the case of dummies for small groups, the memory and speed lag severely. I'm honestly not sure there's a way around this problem as the method itself requires many calculations, in particular for the degrees of freedom correction.

**Comment by nfultz** [comment]
Sparse Matrices maybe? For designs of dummy variables, density is 1/k, so
for k > 3 it's a win. Also, if we know the design isn't cross classified,
we can use some divide-and-conquer strategies.

**Comment by lukesonnet** [comment]
This is implemented for CR2 (clubSandwich), but I need to check with `stata` and check into sparse matrices for performance.

**Comment by lukesonnet** [comment]
Matches stata clustered error with weights. This is closed, only things that would change here would be performance and this isn't the issue for that.
