### ISSUE TITLE
Two-way clustering with fixed effects?

### ISSUE THREAD

**Issue by yukitakahashi1** [DeclareDesign/estimatr#300]
Hi all,
I'm trying to estimate fixed effects model with two-way clustering using lm_robust(), but lm_robust() returns error message. Could we use lm_robust() for two-way clustering?

Example code:
library(estimatr)
library(plm)
data("Produc", package = "plm")
lm_robust(log(gsp) ~ log(pcap) + log(pc) + log(emp) + unemp, data = Produc, fixed_effects = ~ state, clusters = c(state,year),se_type = "CR0")

**Comment by nfultz** [comment]
You can cluster by state/year combo, but it will be somewhat different than a true two-way clustered standard error:

    lm_robust(..., clusters = interaction(state,year), se_type = "CR0")

I believe this would still be a conservative estimate, especially if your data is not balanced - @lukesonnet thoughts?

**Comment by lukesonnet** [comment]
That's right. We do not support two-way clustering at the moment. Unfortunately, it isn't a high priority at the moment either. I am uncertain about the properties of the estimator with pasted version of the clusters, as @nfultz suggested, but it certainly would admit estimating more of the covariance terms.

**Comment by yukitakahashi1** [comment]
I see. Do you by chance know any other R package that supports two-way clustering with fixed effects?

**Comment by lukesonnet** [comment]
No, unfortunately I'm not aware. reghdfe in stata may have the solution you're looking for.

**Comment by yukitakahashi1** [comment]
I see. Hmm..., I was migrating from Stata, so thought it's nice to have something Stata-equivalent R code.
But really helpful discussion - thanks a lot!

**Comment by kuldeepnyadav** [comment]
Looking into fixest package for  two-way clustering with fixed effect. I think it might be promising. 

https://cran.r-project.org/web/packages/fixest/vignettes/fixest_walkthrough.html

**Comment by kuldeepnyadav** [comment]
> I see. Do you by chance know any other R package that supports two-way clustering with fixed effects?

fixest package

**Comment by yukitakahashi1** [comment]
Thank you @kuldeepnyadav!

**Comment by ngreifer** [comment]
Just saying that I would also like the option for multi-way clustered SEs. They can be computed easily using the `sandwich` package, so the infrastructure is there.
