### ISSUE TITLE
rlang warnings

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/estimatr#307]
With the new version of rlang 0.4.0, many estimatr functions return warnings i.e. 

```
n <- 40
  dat <- data.frame(
    y = rnorm(n),
    bl = rep(1:5, each = 8),
    z = 1:4,
    ps = runif(n)
  )

> horvitz_thompson(y ~ z, data = dat, subset = z <= 2, condition_prs = ps)
Assigning non-quosure objects to quosure lists is deprecated as of rlang 0.3.0.
Please coerce to a bare list beforehand with `as.list()`
```

This comes from line 39, helper_clean_model_data.R (at least):

```
mfargs[[da]] <- sym(name) 
```

**Comment by graemeblair** [comment]
fyi we are preparing a patch for DeclareDesign fixing rlang 0.4.0 warnings, would be great to get this into this upcoming patch if possible

**Comment by lukesonnet** [comment]
Has any work on the DeclareDesign package been done? If not, I may have time later in the week to start it here which should be helpful for whoever does DD.

**Comment by graemeblair** [comment]
Yes -- we've squashed the DD warnings as far as we can tell and just need the ones emanating from estimatr squashed. Thank you!

**Comment by acoppock** [comment]
So we're stuck on this one!  We tried changing this in helper_clean_model_data.R, line 39

```
  for (da in to_process) {
    name <- sprintf(".__%s%%%d__", da, sample.int(.Machine$integer.max, 1))
    m_formula_env[[name]] <- eval_tidy(mfargs[[da]], data = data)
    mfargs[[da]] <- sym(name)
  }
``` 

we tried:

```
mfargs[[da]] <- enquo(name)
```

This successfully avoided the warning... but of course it didn't work when actually evaluated.

Any help @nfultz or @lukesonnet ?  Thank you so much if you have a second to look at this.

**Comment by nfultz** [comment]
You want the value of name:

    mfargs[[da]] <- quo(!!name)

Is what I would try next.

**Comment by graemeblair** [comment]
Thanks @nfultz. We tried each of these. To record as we continue to look into it, we get this error.

```
eval_tidy(quo((stats::model.frame)(
+     !!!mfargs,
+     data = data,
+     na.action = na.omit_detailed.data.frame,
+     drop.unused.levels = TRUE
+   )))
Error in model.frame.default(terms(formula, lhs = lhs, rhs = rhs, data = data,  : 
  invalid type (language) for variable '(condition_pr)'
```

**Comment by lukesonnet** [comment]
Hi all, I'll dedicate a few hours to these warnings today and some other maintenance.
