### ISSUE TITLE
Feature Request: Compatibility with emmeans

### ISSUE THREAD

**Issue by DeFilippis** [DeclareDesign/estimatr#309]
It would be nice to add support for the `emmeans` library to enable sophisticated post-estimation tools.  The current linearHypothesis method from the `car` library is a bit inflexible for all but the simplest linear tests. 

There's a vignette on how to enable package support here: https://cran.r-project.org/web/packages/emmeans/vignettes/xtending.html

There is also the function `qdrg()` function which might be used as a temporary measure, but I couldn't get it to work.  https://www.rdocumentation.org/packages/emmeans/versions/1.3.5/topics/qdrg

Any thoughts on how to get this to work?  How hard does implementing compatibility look?

**Comment by lukesonnet** [comment]
This is now implemented thanks to #314 by @rvlenth, the emmeans author!

In the GitHub version, hopefully on CRAN by end of month.
