### ISSUE TITLE
Big numbers + fixed effects

### ISSUE THREAD

**Issue by NickCH-K** [DeclareDesign/estimatr#312]
Haha it's me again, hope you're not sick of me yet!

I was in the process of preparing a video on estimatr and randomly came across a surprising issue:

If some of the numbers in the regression are *big*, and you specify `fixed_effects`, then `lm_robust` and `iv_robust` become extremely slow. When I ran this on my laptop it actually made the "break" button not work and froze R - I had to use the Task Manager to quit. When I ran it on RStudio.cloud it similarly hung for a long time, but the break button still worked so I was able to stop it. This is `estimatr 0.18.0`.

```
library(Ecdat)
library(estimatr)

data("Cigarette")

#note how large the numbers are in income
summary(Cigarette$income)
##     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## 6769883  25100460  61692010  99245556 118084118 771470144 

#These work fine
m1 <- lm_robust(packpc~income,data=Cigarette)
m1 <- lm_robust(packpc~income,clusters=state,data=Cigarette)

#This hangs R
m1 <- lm_robust(packpc~income,fixed_effects=~state,data=Cigarette)

#This works fine, indicating that it is indeed the size of the numbers fed into lm_robust that's the problem
m1 <- lm_robust(packpc~I(income/1000000),fixed_effects=~state,data=Cigarette)
```

These same problems occur for `iv_robust` too.

And just to pin down that it seems to be the level size of the numbers and not, say, high levels of variation or something weird about `Cigarette`:

```
# This runs fine
df <- data.frame(i = rep(1:100,1000),x=rnorm(100000)*1000000,y=rnorm(100000))
m1 <- lm_robust(y~x,data=df,fixed_effects=~i)

# This hangs
df <- data.frame(i = rep(1:100,1000),x=rnorm(100000)*1000000+10000000,y=rnorm(100000))
m1 <- lm_robust(y~x,data=df,fixed_effects=~i)
```

**Comment by nfultz** [comment]
Thank you for reporting this and providing an example, we will take a look.

**Comment by NickCH-K** [comment]
Checked in estimatr 0.20.0, bug is still there (as I'd expect given the issue is open, but figured I'd check).

**Comment by lukesonnet** [comment]
The problem is that `eps` for the convergence of the demeaning of the design matrix is too large; it needs to scale with the norm of the covariates. I've implemented a fix but it needs tweaking to ensure that it does not cause other edge case problems.
