### ISSUE TITLE
modelsummary not working

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/estimatr#324]
I've been banging my head trying to get modelsummary to work and there's something wrong with how I've set it up. I can't reproduce the errors that travis is getting in `R CMD CHECK`. @lukesonnet perhaps you can take a look. I made the "various fixes" PR to separate various travis and R CMD CHECK things from the very simple PR for modelsummary. I get no errors when running the modelsummary2 branch on my machine.

**Comment by lukesonnet** [comment]
Seems the problem is that Travis can't get gt. Let's wait to support this until `gt` is on CRAN anyways, and hopefully that'll clear up this problem as a by product.
