### ISSUE TITLE
missing functions

### ISSUE THREAD

**Issue by ylelkes** [DeclareDesign/estimatr#332]
a number of functions don't appear when i install estimatr, either from cran or this site. In particular, starprep and its helper functions are missing. It worked on my mac but not on my ubuntu machine. thanks.

**Comment by nfultz** [comment]
Can you post your `sessionInfo()` ?

**Comment by ylelkes** [comment]
![Screenshot from 2019-10-07 16-21-43](https://user-images.githubusercontent.com/1694330/66345746-a5b67680-e91e-11e9-9a44-67c16523901c.png)

**Comment by nfultz** [comment]
You have a very old version of both R and estimatr - I recommend you upgrade both. See https://cran.r-project.org/bin/linux/ubuntu/README.html for directions on updating R for Ubuntu LTS versions.

**Comment by ylelkes** [comment]
thanks, that worked. appreciate it!
