### ISSUE TITLE
move clubSandwich to optional in tests

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/estimatr#357]
From Brian Ripley at CRAN:

We have asked for an update fixing the check problems shown at
   <https://cran.r-project.org/web/checks/check_results_clubSandwich.html>
with no response from the maintainer thus far.  It is now scheduled for
archival on 2020-08-06.

Packages

     estimatr lavaSearch2 panelr parameters plm

suggest clubSandwich but do not use it conditionally and fail their
checks without it (see 'Writing R Extensions' §1.1.3.1).

Please correct before 2020-08-06 to safely retain your package on CRAN
(whether or not clubSandwich is updated before then, and do ensure all
the other packages you suggest are used conditionally).

**Comment by nfultz** [comment]
Linked PR fixes it for clubSandwich, but someone should check for all the other Suggests.
