### ISSUE TITLE
``lm_robust`` object does not provide some accessors

### ISSUE THREAD

**Issue by jlgraves-ubc** [DeclareDesign/estimatr#384]
Hi there,

I'm trying to do some work with this package, particularly for people who mainly use STATA and the ``lm_robust`` function is wonderful.  However, the object it returns it doesn't seem to provide some of the standard accessor functions that ``lm`` does, which means it breaks other packages that rely on those functions.  In particular, I have noticed that:

* ``deviance`` and ``residuals`` both return ``NULL``  
* ``coefficients`` works fine

There might be some other ones, but these were the ones I was working with.  Am I mistaken or are these not associated with the object?

**Comment by nfultz** [comment]
duplicate of #123 and / or #345 ?

**Comment by jlgraves-ubc** [comment]
Yes, I think so!  Thanks for tagging those.
