### ISSUE TITLE
Error when adding lots of dummy variables

### ISSUE THREAD

**Issue by lukesonnet** [DeclareDesign/estimatr#53]
In some standard FE models, `lm()` doesn't fail (or even return NAs for coefficients) while `lm_robust()` will fail saying the (X'X) is singular.

I can't come up with a simple MWE, but I have an example in my own data to work off of.

**Comment by nfultz** [comment]
https://github.com/DeclareDesign/estimatr/blob/master/src/lm_robust_helper.cpp#L68-L74

This lines could be reparamterized / refactored for better numerical
stability.

**Comment by lukesonnet** [comment]
Do you have anything particular in mind (e.g. the cholesky decomposition route).

**Comment by lukesonnet** [comment]
Armadillo doesn’t have any functions that take advantage of basic BLAS routines to invert upper triangular matrices, which is a big advantage of solving LS using QR or Cholesky decompositions.

However, RcppEigen exists to facilitate use of Eigen (much like RcppArmadillo). Eigen has built in functions that allow me to take advantage of the cholesky decomposition to get (X’X)^-1.

This should help solve our numerical instability problem (I will try to get a MWE where the old method fails), and not only that, check this out:

```{r}
## Install test version
devtools::install_github('DeclareDesign/estimatr', ref = 'lukesonnet/lm_speed')
library(estimatr)

dat <- fabricatr::fabricate(
  N = 1000,
  blocks = as.factor(rep(1:(N/2), each = 4)),
  x = rnorm(N),
  y = rnorm(N)
)

## Lots of dummy variables
X <- model.matrix(y ~ x + blocks, data = dat)

## Old version, armadillo
## XtX_inv = (X'X)^-1
microbenchmark::microbenchmark(
  lm_robust_helper(
    y = dat$y,
    X = X,
    Xunweighted = NULL,
    weight = NULL,
    weight_mean = 1,
    cluster = NULL,
    ci = TRUE,
    type = 'none',
    which_covs = c(T, T)
  ),
  times = 20
)
```
```
Unit: milliseconds
expr
 lm_robust_helper()
      min       lq     mean   median       uq      max neval
 585.0181 629.1965 663.0072 642.1482 702.2645 781.4249    20
```
```{r}
## New version, Eigen
## Where L is from the LL' cholesky decomposition
## XtX_inv = (L^{-1})' L
microbenchmark::microbenchmark(
  lm_robust_helper_eigen(
    y = dat$y,
    X = X,
    Xunweighted = NULL,
    weight = NULL,
    weight_mean = 1,
    cluster = NULL,
    ci = TRUE,
    type = 'none',
    which_covs = c(T, T)), 
  times = 20
)
```
```
Unit: milliseconds
expr
 lm_robust_helper_eigen()
      min       lq     mean   median       uq      max neval
 107.7478 112.0547 132.2608 117.4409 126.9066 251.7868    20
```

That's a 5x speed improvement.

There are a few paths forward:

- We add the RcppEigen dependency remove the RcppArmadillo hooks and I rewrite all the C++ code to fit that (keeps dependencies lower, obviously provides some speed boosts, but Eigen probably doesn't strictly dominate Armadillo. This is just a specific case that Armadillo isn't great for)
- We add RcppEigen and keep both dependencies
- I write a manual backsolver for RcppArmadillo so we can use QR decomposition quickly in RcppArmadillo (will still be slower based on other people's simulations)

I think the first is the way to go, but it's not the cheapest re: my time.

**Comment by acoppock** [comment]
holy moly.

Matrix inversion is easily the most expensive task and the whole point of estimatr is its really fast.  So lets make the switch to RcppEigen.

Luke, your time is valuable, but if it *were* possible to depend only on RccpEigen, I think that would be good for the Malawi problem.

**Comment by lukesonnet** [comment]
I agree it's the best solution.

I also now believe the problem is simply that `lm()` just drops collinear variables until X is no longer rank deficient while we have no such mechanism. I guess I thought `model.matrix()` did this, but I was obviously very wrong. MWE:

```{r}
x1 <- rnorm(10)
x2 <- x1
y <- rnorm(10)
estimatr::lm_robust(y ~ x1 + x2) #errors
summary(lm(y ~ x1 + x2)) # just drops x2
```

**Comment by lukesonnet** [comment]
R does this using a "rank-revealing" form of QR. This can be done in Eigen. I'll have to go that route, then.

**Comment by lukesonnet** [comment]
Closing this for a cleaner issue.
