### ISSUE TITLE
Dealing with rank-deficient X matrices (and speed improvements to lm_robust)

### ISSUE THREAD

**Issue by lukesonnet** [DeclareDesign/estimatr#56]
Currently, `lm_robust()` fails when people pass a rank-deficient matrix. `model.matrix()` takes care of a lot of these problems, but not all of them, and often with messy data, lots of dummy variables, or some other edge cases, users will still get design matrices that are rank-deficient.

`lm()` currently handles this using a rank-revealing QR decomposition, and allows it to go ahead with a note. See how it does on the following:
```{r}
n <- 10
X <- cbind(1, 2, rnorm(n))
y <- rnorm(n)
summary(lm(y~X+0))
```
```{r}
Call:
lm(formula = y ~ X + 0)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.2680 -0.6358 -0.1516  0.2116  2.6752 

Coefficients: (1 not defined because of singularities)
    Estimate Std. Error t value Pr(>|t|)
X1 -0.163576   0.383550  -0.426    0.681
X2        NA         NA      NA       NA
X3 -0.003863   0.521907  -0.007    0.994

Residual standard error: 1.212 on 8 degrees of freedom
Multiple R-squared:  0.02224,	Adjusted R-squared:  -0.2222 
F-statistic: 0.09098 on 2 and 8 DF,  p-value: 0.914
```
It warns that 1 was not defined because of singularities, and puts NA for all of those values, and ignores them in all other calculations (i.e. `vcov(lmo)` will just return a 2x2 in this case and ignore the dropped variable).

**Question:** I think we should essentially mimic this functionality. `lm()` has a `singular.ok = TRUE` default, that I think we should copy with the `singular_ok` or `strict`. However, a question is whether we should default to allowing singularities or erroring instead. Defaulting to erroring might be annoying for some, but it's a little less sneaky that your data aren't well behaved. I vote to default to pass, but I'd like to warn in the call, not just the summary like lm does. Thoughts?

------
Currently, we have no support for rank-deficient X matrices. I've written code that does the following:

1. Try LLT cholesky decomposition (fastest)
2. Does cholesky decomposition thinks that the matrix is full rank?
    * If yes, proceed with solution using cholesky decomposition
    * If no, proceed with solution using rank-revealing QR decomposition

Now, if X is full-rank, we are as fast as we can be. If X is rank deficient, it would be best to just go straight to the RRQR decomposition.

Therefore, a **question:** Do we allow people to let us _know_ that something is rank-deficient, and so they can pass a flag telling us this and we go straight to QR?

Re: whether LLT can tell whether something is full rank, it seems like NO, from [here](http://simbaforrest.github.io/blog/2016/03/25/LDLT-for-checking-positive-semidefinite-matrix-singularity.html#id-can-we-use-ldlt-to-check-whether-a-psd-matrix-is-numerically-singular-or-not). However, we don't actually need to know whether is full rank, but whether LLt is worried it might not be, and it passes a flag that covers just that. It seems like the Eigen people think it will warn in that case, and it works in some toy examples.

Nonetheless, is it too risky to try the cholesky? Should we go straight for QR? I can't really evaluate these claims.

-------

Here are some speed comparisons to help you out (N = 1000, p = 20),

Rank-deficient matrix (two vars):
Eigen LLT -> QR: 381ms
Eigen QR: 276ms
Old: NA (can't do it)

Full rank matrix:
Eigen LLT -> QR (basically just LLT): 188ms
Eigen QR: 333ms
Old: 414ms

**Comment by lukesonnet** [comment]
I've added the functions to lm_speed.cpp for now in the lukesonnet/lm_speed branch. Note you have to call the directly, they aren't hooked up to `lm_robust()`.

**Comment by lukesonnet** [comment]
We decided to try for the following route with an option like `method =' (retry doesn't make sense for the tree options).

`method = 'chol qr'` (default)
1. Try LLT cholesky decomposition (fastest)
2. Does cholesky decomposition thinks that the matrix is full rank?
    * If yes, proceed with solution using cholesky decomposition
    * If no, proceed with solution using rank-revealing QR decomposition

`method = 'chol only'` (default)
1. Try LLT cholesky decomposition (fastest)
2. If matrix is full rank, continue, else error

`method = 'qr only'` (default)
1. Use rank-revealing QR decomposition

------

One problem here is that I'm having trouble finding a fast way to subset the clusters with Eigen. Current solution is far too slow and makes clustered SEs very, very slow. I'll look to overcome this as having both RcppEigen and RcppArmadillo is probably too heavy a set of dependencies.

**Comment by lukesonnet** [comment]
I've opted for the one flag route `trychol = TRUE`, which I think is the best, and we can discuss today.

Closed by #65

**Comment by graemeblair** [comment]
Great. Can you name it `try_cholesky` to match other args and not be cryptic?

**Comment by lukesonnet** [comment]
That argument is updated.

Also documenting here (and will briefly in docs) that the reason we differ from the QR in R is that they modified the QR decomposition and left this hilarious note about how they did so (h/t @nfultz):

``
C     Dqrdc2 is a *modification* of Linpack's dqrdc ('DQRDC') for R
c
c     dqrdc2 uses householder transformations to compute the qr
c     factorization of an n by p matrix x.  a limited column
c     pivoting strategy based on the 2-norms of the reduced columns
c     moves columns with near-zero norm to the right-hand edge of
c     the x matrix.  this strategy means that sequential one
c     degree-of-freedom effects can be computed in a natural way.
c
c     i am very nervous about modifying linpack code in this way.
c     if you are a computational linear algebra guru and you really
c     understand how to solve this problem please feel free to
c     suggest improvements to this code.
c
c     Another change was to compute the rank.
c
c     original (dqrdc.f) linpack version dated 08/14/78 .
c     g.w. stewart, university of maryland, argonne national lab.
c
C     This version dated 22 August 1995
C     Ross Ihaka
```

So unless we steal this algorithm we are stuck with what we have, and I think that's acceptable.
