### ISSUE TITLE
Undocumented default for draw_rs

### ISSUE THREAD

**Issue by nfultz** [DeclareDesign/estimatr#57]
What is this doing? Let's add an explanation to the Rd.

```
draw_rs(N=10, clust_var=gl(5,2))
 [1] 0 0 1 1 1 1 1 1 0 0
```

**Comment by acoppock** [comment]
Whoa, I’ve never seen the `gl` function before!  Let’s just please remove and do something more transparent instead, e.g., factor(rep(1:5, each = 2))

**Comment by nfultz** [comment]
Sure, but why were the three clusters choosen? Is there a hidden default of p=.5 or something?

**Comment by acoppock** [comment]
Ah. Didn’t realize that’s what you meant.  Yes, it defaults to p = 0.5.

**Comment by lukesonnet** [comment]
Is this an estimatr issue?

**Comment by nfultz** [comment]
Whoops, wrong repo.
