### ISSUE TITLE
Rstudio yellow squigglies

### ISSUE THREAD

**Issue by acoppock** [DeclareDesign/estimatr#58]
When I'm using lm_robust, everything works great! 

But rstudio is upset. It has a yellow triangle and a yellow squiggly underline.

When I hover over it says

argument 'weights' is missing, with no default 
argument 'subset' is missing, with no default 
argument 'clusters' is missing, with no default 

maybe some NSE thing?

**Comment by lukesonnet** [comment]
This seems like an RStudio problem. I can't reproduce this. What version are you using?

**Comment by graemeblair** [comment]
@acoppock is this still happening?

**Comment by lukesonnet** [comment]
Still can't replicate this, @acoppock?

**Comment by acoppock** [comment]
ok nm.
