### ISSUE TITLE
Ad DV name to tidy output

### ISSUE THREAD

**Issue by acoppock** [DeclareDesign/estimatr#59]
It'd be awesome if there were a column in the output called `dv` that reported the name of the dependent variable.

hashtag feature request.

**Comment by acoppock** [comment]
I was thinking of adding a `dv` column to the tidy output of `lm_robust` and other estimators. right now the output looks like this:

```
 coefficient_name       est        se           p   ci_lower  ci_upper  df
1      (Intercept) 0.2222222 0.1008317 0.028978271 0.02307035 0.4213741 158
2   swap_treatment 0.2918623 0.1092642 0.008350522 0.07605537 0.5076692 158
```

**Comment by nfultz** [comment]
:+1: - keep getting confused on which ticket is which repo, I mostly reply to these in gmail, if the text doesn't say it's pretty hard to tell.

**Comment by lukesonnet** [comment]
Do you really want this? Can I add it as an attribute or do you want it to be more visible.

**Comment by acoppock** [comment]
I think it should be in the data.frame, not an attribute.

It’s something that I’m *constantly* adding when preparing model fits for either meta analysis or plotting.  It’s also a good thing to remind users in the output what they were regressing on what!

Thanks!

**Comment by lukesonnet** [comment]
can I call it `outcome` rather than `dv`? Your call.

**Comment by lukesonnet** [comment]
Added in #62
