### ISSUE TITLE
lm_lin for multi-valued treatments

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/estimatr#66]
`lm_lin` supports binary treatments; seems like wouldn't be too hard to do same formula editing for multiple-valued treatments. should we? @acoppock @lukesonnet

**Comment by lukesonnet** [comment]
No, I think this would be relatively simple to implement. Maybe we discuss tomorrow whether to implement (and then decide how to order/present the results?).

**Comment by lukesonnet** [comment]
This is implemented in PR #75. I'll close this once @nfultz is able to review.
