### ISSUE TITLE
"outcome" missing when calling lm_robust_fit directly

### ISSUE THREAD

**Issue by acoppock** [DeclareDesign/estimatr#72]
happy new year!

MWE:

```
X <- matrix(c(1, 1, 1, 1, 2, 3), ncol = 2)
y <- c(3,  4, 3)
test <- lm_robust_fit(y = y, X = X, 
              cluster = NULL, 
              se_type = "none", 
              coefficient_name = "X2", 
              weights = NULL, ci = FALSE,
              alpha = 0.05, 
              return_vcov = FALSE, trychol = FALSE)

test$est
test$outcome
```

this means that `tidy(test)` errors.

I didn't know where to fix because of `lm_return`

I think that the "outcome" should just be whatever variable is supplied to `y`

THANKS

**Comment by nfultz** [comment]
I think you have to go through the formula interface to get the extra columns - I think that this is symptomatic of the object hierarchy being muddy - eg if lm_robust_fit does not return a "full" lm_robust object, we should provide an appropriate `tidy()` generic for that also.

**Comment by acoppock** [comment]
Option 1: a `tidy` for `lm_robust_fit` objects that somehow extracts the outcome name from whatever is supplied to `y`

Option 2: Just initialize the [[outcome]] list entry in the lm_robust_fit object with something that may or may not get overwritten by the formula object?

**Comment by acoppock** [comment]
@lukesonnet what say you?

**Comment by lukesonnet** [comment]
I'm not sure what the best solution is in terms of having a clear hierarchy. I'd rather not provide S3 methods for things that should be internal, but that we are exposing for tinkerers.

Therefore I'd prefer option 2.

**Comment by lukesonnet** [comment]
We've decided to make sure `lm_robust_fit` has enough stuff so that if a user manually calls `tidy.lm_robust(lm_robust_fit(...))` that it will work.
