### ISSUE TITLE
vignette on output using texreg, xtable, and apsrtable 

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/estimatr#74]
(also, not doing stargazer for now)

**Comment by nfultz** [comment]
@lukesonnet this is the magic incantation to make texreg work with the default `lm` handler -

**Comment by graemeblair** [comment]
flagging this for sending the xtable bit upstream now to prep for v2

**Comment by lukesonnet** [comment]
Closed by @acoppock via #206
