### ISSUE TITLE
duplicate coefficient_name option in DD & estimatr

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/estimatr#93]
We have the option `coefficient_name` in `declare_estimator` and `lm_robust` (and `lm_lin`). In both cases, it just subsets the output df. We definitely need it in `declare_`, we don't strictly need it in lm_robust. They don't (I think) conflict, because declare_estimator will just not pass on the coefficient_name option.

**Comment by nfultz** [comment]
I'm fine with dropping this from estimatr, and having it only in DD.

**Comment by lukesonnet** [comment]
@acoppock, what say you? I think you use this feature the most?

**Comment by lukesonnet** [comment]
I should say, the biggest draw back for me here is I have to rewrite a lot of tests that take advantage of this.

**Comment by acoppock** [comment]
I don't think we need to have the option to subset in estimatr.  Subsetting only in DD seems like the right thing to do.

**Comment by lukesonnet** [comment]
Ok it's gone.
